### ISSUE TITLE
GitRevisionInfo.h isn't created on Linux

### ISSUE THREAD

**Issue by nephatrine** [QwazyWabbitWOS/lmctf60#7]
When I'm building this on Linux, I get this error now:

```
#24 0.868 g_save.c:9:10: fatal error: GitRevisionInfo.h: No such file or directory
#24 0.868     9 | #include "GitRevisionInfo.h"
#24 0.868       |          ^~~~~~~~~~~~~~~~~~~
```

Looks like this was added in commit 5031b04. I see that in `g_local.h` this include is guarded to only occur on Windows so probably something similar needs to be done in `g_save.c`.

I'm also assuming the makefile should be passing `REV` and `VER` as `LMCTF_REVISION` and `LMCTF_VERSION` definitions? Alternatively, it shouldn't be difficult to add a makefile step that just builds `GitRevisionInfo.h` using sed or whatever to fill in those variables in the template you defined and then you could just unconditionally include that.

**Comment by nephatrine** [comment]
I just opened PR https://github.com/QwazyWabbitWOS/lmctf60/pull/8 - feel free to reimplement yourself or apply some other fix though.

**Comment by QwazyWabbitWOS** [comment]
Thanks, that's a great solution.
